### ISSUE TITLE
Module build failed (from ./node_modules/babel-loader/lib/index.js):

### ISSUE THREAD

**Issue by Kaushik-Roy** [scandipwa/installer#13]
Hi All, 

I am facing a error during 'npm run build' command. Please let me know what to do for this issue.

Also a similar error i mentioned in this blog [https://stackoverflow.com/questions/62558086/babel-loader-and-pluginpass-callexpression-error](url) 

My System details:

> Ubuntu 18.04
> Magento 2.3.3 (fresh installation)
> Node v10.22.0
> NPM 6.14.6 
> Server version: Apache/2.4.29 (Ubuntu)
> varnishd (varnish-5.2.1 revision 67e562482)
> redis-cli 6.0.5

I have also attached my composer.json, package.json, package-lock.json file :

[composer.json.txt](https://github.com/scandipwa/installer/files/4980896/composer.json.txt)
[package.json.txt](https://github.com/scandipwa/installer/files/4980897/package.json.txt)
[package-lock.json.txt](https://github.com/scandipwa/installer/files/4980898/package-lock.json.txt)

Below are the errors:

`ERROR in /var/www/html/m233a.vn/vendor/scandipwa/source/src/app/component/CheckoutPayments/CheckoutPayments.component.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: /var/www/html/m233a.vn/vendor/scandipwa/source/src/app/component/CheckoutPayments/CheckoutPayments.component.js: Cannot read property 'value' of undefined at PluginPass.CallExpression (/var/www/html/m233a.vn/app/design/frontend/Scandiweb/pwa/node_modules/babel-plugin-console-source/index.js:30:47)
ERROR in /var/www/html/m233a.vn/vendor/scandipwa/source/src/app/component/Klarna/Klarna.component.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: /var/www/html/m233a.vn/vendor/scandipwa/source/src/app/component/Klarna/Klarna.component.js: Cannot read property 'value' of undefined
ERROR in /var/www/html/m233a.vn/vendor/scandipwa/source/src/app/route/SomethingWentWrong/SomethingWentWrong.component.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: /var/www/html/m233a.vn/vendor/scandipwa/source/src/app/route/SomethingWentWrong/SomethingWentWrong.component.js: Cannot read property 'value' of undefined at PluginPass.CallExpression (/var/www/html/m233a.vn/app/design/frontend/Scandiweb/pwa/node_modules/babel-plugin-console-source/index.js:30:47)`

Below is the complete screenshot of the error:

![scandi-pwa-error-1](https://user-images.githubusercontent.com/18119362/88521024-016b0100-d012-11ea-8e78-f33a0cf09877.png)

**Comment by Kaushik-Roy** [comment]
Hi All, 
I was able to resolve this issue by updating my package.json dependencies with original dependencies from core files.
Below are the core files:
- /vendor/scandipwa/source/package.json
- /vendor/scandipwa/source/package-lock.json

Below is a diff of my package.json file:


![scandipwa-issue-2](https://user-images.githubusercontent.com/18119362/88643145-f92cc780-d0de-11ea-8961-f0b498c2ea22.png)
